Frontend-Web/Pages/Create.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

using todolist.Models;


namespace todolist.Create
{
    public class CreateModel : PageModel
    {
        private readonly HttpClient _http;
        public CreateModel(HttpClient http)
        {
            _http = http;
        }

        [BindProperty]
        public ToDoTask Task{get; set;} = new();
        public IActionResult OnGet()
        {
            return Page();
        }

        public async  Task<IActionResult> OnPostAsync()
        {
            if(!ModelState.IsValid) return Page();
            var jwt = HttpContext.Request.Cookies["jwt_session"];
            var httpReqMsg = new HttpRequestMessage(HttpMethod.Post, "http://localhost:5005/todo/create")
            {Content = JsonContent.Create(new {title = Task.Title, description = Task.Description})};
            httpReqMsg.Headers.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", jwt);
            var response = await _http.SendAsync(httpReqMsg);
            var statusCode = response.StatusCode;
            var responseBody = await response.Content.ReadAsStringAsync();
            if (!response.IsSuccessStatusCode)
            {
                ModelState.AddModelError("", $"API Error: {statusCode} | {responseBody}");
                return Page();
            }
            Console.WriteLine(response);
            return RedirectToPage("/index");
        }
    }  
}

Frontend-Web/Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Frontend_Web.Pages;

[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
[IgnoreAntiforgeryToken]
public class ErrorModel : PageModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

    public void OnGet()
    {
        RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
    }
}

Frontend-Web/Pages/Index.cshtml.cs
using System.Security.Cryptography.X509Certificates;
using DTO;
using todolist.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Net.Http.Headers;

namespace Frontend_Web.Pages;

public class IndexModel : PageModel
{
    public List<ToDoItem> Items { get; private set; } = new();

    private readonly IHttpClientFactory _httpClientFactory;
    private readonly HttpClient _http;
    public IndexModel(IHttpClientFactory httpclientFactory, HttpClient http)
    {
        _http = http;
        _httpClientFactory = httpclientFactory;
    }
    public string? Username { get; private set; }
    public async Task<IActionResult> OnGet()
    {
        Username = HttpContext.Items["Username"] as string;

        string? jwt = HttpContext.Request.Cookies["jwt_session"];
        var req = new HttpRequestMessage(HttpMethod.Get, "http://localhost:5005/todo/get");
        req.Headers.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", jwt);
        var resp = await _http.SendAsync(req);
        if(!resp.IsSuccessStatusCode)
        {
           return Page();
        }
        Items = await resp.Content.ReadFromJsonAsync<List<ToDoItem>>() ?? new List<ToDoItem>();
        return Page();
    }

    public async Task<IActionResult> OnPostDeleteAsync(int id)
    {
        var jwt = Request.Cookies["jwt_session"];

        var request = new HttpRequestMessage(
            HttpMethod.Delete,
            $"http://localhost:5005/todo/delete/{id}"
        );

        request.Headers.Authorization =
            new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", jwt);

        var response = await _http.SendAsync(request);

        if (!response.IsSuccessStatusCode)
        {
            Console.WriteLine(await response.Content.ReadAsStringAsync());
        }
        return RedirectToPage();
    }

    public async Task<IActionResult> OnPostToggleStatusAsync(int id)
    {
        Console.WriteLine("Procced");
        var jwt = Request.Cookies["jwt_session"];

        var request = new HttpRequestMessage(
            HttpMethod.Put,
            $"http://localhost:5005/todo/update/{id}"
        );

        request.Headers.Authorization =
            new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", jwt);

        var response = await _http.SendAsync(request);

        if (!response.IsSuccessStatusCode)
        {}
        return RedirectToPage();
    }
}

Frontend-Web/Pages/Create.cshtml
@page
@model todolist.Create.CreateModel
@{}



<h1>Create Task</h1>
<div class="container border" style="padding:20px;">
    <form method="POST">
    <div class="form-group row mb-1">
            <span class="text-danger" asp-validation-for="Task.Title"></span>
            <div class="col-2">
                <label asp-for="Task.Title"></label>
            </div>
            <div class="col-5">
                <input type="text" asp-for="Task.Title" class="form-control" style="background-color: rgb(19, 19, 19); color: white;">
            </div>
        </div>
        <div class="form-group row mb-1">
            <span class="text-danger" asp-validation-for="Task.Description"></span>
            <div class="col-2">
                <label asp-for="Task.Description"></label>
            </div>
            <div class="col-5">
                <input type="text" asp-for="Task.Description" class="form-control" style="background-color: rgb(19, 19, 19); color: white;">
            </div>
        </div>
        <div class="text-danger" asp-validation-summary="ModelOnly" style="list-style:none; padding-left:0;"></div>
        <div class="form-group row mb-1">
            <div class="col-2">
                <input type="submit" class="btn btn-primary" value="Create">
            </div>
        </div>
    </form>
</div>

Frontend-Web/Pages/Edit.cshtml
@page "{id:int}"
@model todolist.Edit.EditModel
@{}



<h1>Edit Task</h1>
<div class="container border" style="padding:20px;">
    <form method="POST">
    <div class="form-group row mb-1">
            <span class="text-danger" asp-validation-for="Task.Title"></span>
            <div class="col-2">
                <label asp-for="Task.Title">Title</label>
            </div>
            <div class="col-5">
                <input type="text" asp-for="Task.Title" class="form-control" style="background-color: rgb(19, 19, 19); color: white;">
            </div>
        </div>
        <div class="form-group row mb-1">
            <span class="text-danger" asp-validation-for="Task.Description"></span>
            <div class="col-2">
                <label asp-for="Task.Description">Description</label>
            </div>
            <div class="col-5">
                <input type="text" asp-for="Task.Description" class="form-control" style="background-color: rgb(19, 19, 19); color: white;">
            </div>
        </div>
        <div class="text-danger" asp-validation-summary="ModelOnly" style="list-style:none; padding-left:0;"></div>
        <div class="form-group row mb-1">
            <div class="col-2">
                <input type="submit" class="btn btn-primary" value="Save">
            </div>
        </div>
    </form>
</div>

Frontend-Web/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}
<div class="text-center">
    <h1 class="display-4">Welcome  @Model.Username</h1>
    <p><a href="/create">Create To Do Item</a></p>
    @if (Model.Items.Any())
    {
        
        <table class="table table-striped table-hover align-middle">
            <tr style="vertical-align:top">
                <th>Title</th>
                <th style="padding-left: 1.2rem; padding-right: 1.2rem;">Description</th>
                <th>Completed</th>
                <th>Time Created</th>
            </tr>
            @foreach(var item in Model.Items)
            {
                <tr style="vertical-align:bottom">
                    
                        <td>@item.Title</td>
                        <td>@item.Description</td>
                        <td><form method="post" asp-page-handler="ToggleStatus" asp-route-id="@item.ItemId" style="display:inline;"><button type="submit" class="btn btn-link"><input style="pointer-events: none;" type="checkbox" @(item.Completed ? "checked" : "") disabled /></button></form></td>
                        <td style="padding-right: 1.2rem;">@item.CreatedAt</td>
                        <td>
                            <a style="display:inline;" class="btn btn-link" href="/edit/@item.ItemId">Edit</a> | <form method="post" asp-page-handler="Delete" asp-route-id="@item.ItemId" style="display:inline;"><button type="submit" class="btn btn-link">Delete</button></form>
                        </td>
                </tr>
            }
        </table>
    } else{
        <p>No tasks!</p>
    }
</div>

Frontend-Web/Pages/ServiceUnavailable.cshtml
@page

<h1>503 - Service Unavailable</h1>
<p>Is the backend up and running?</p>